pages/code-of-conduct.js

hi @Amanya-Brian @basiima please refer to this for the pages directory

feat: add code of conduct page

---

components/HeroSection.js

feat: add home hero background image

---

app/call-for-sponsors/page.jsx
components/SponsorSection.js

- create a call-for-sponsors page and add sponsorship packages
- add a call-to-action button under sponsors section on homepage which routes to call-for-sponsors

feat: add call-for-sponsors page

---

app/privacy-policy/page.jsx
components/ContactUsSection.js
components/Footer.js

- create privacy policy page
- add route to the footer

feat: add privacy policy page

---

app/page.js
components/Navbar.js
components/VenueSection.js

- commented the event schedule as it depends on the proposals submitted

feat: add event venue location map

---

components/SponsorSection.js

fix route in the sponsors section

fix: route to sponsors page

---

app/health-and-safety/page.jsx
components/Footer.js

create a new page for health and safety guidelines

page: health and safety guidelines

---

app/health-and-safety/page.jsx
components/Footer.js

add health and safety guidelines page

---

README.md

- Improved Run of the ug.pycon.org website locally for new contributors.

docs: readMe addition

---

app/financial-aid/page.jsx
app/page.js

I have updated the Grants page using the content from Django con Africa

updated financial aid instructions

---

app/shop/page.jsx

Update: Added instructions on the merch page (shop)

---

app/shop/page.jsx
components/shop/data.js
components/shop/step.jsx

Reverts PyconUg/ug.pycon.org#64

Fix: Added instructions on the merch page (shop)

---

components/ui/navbar.js

Created about PyCon Ug menu item and added the Code of conduct and health and safety guidelines pages

Added dropdown

---

app/django-girls/page.jsx
app/speakers/[speaker]/page.jsx
app/speakers/page.jsx
components/speakers/speaker-card.jsx
components/speakers/speakers-data.js
components/speakers/title-section.jsx
components/ui/sections/page-section.jsx

feat: Speakers pages

---

app/django-girls/page.jsx
utils/constants.js

The second link for "Become a coach" is copied from the Official Django girls kampala page.

Update: Added Registration form for Django girls

---

components/home/jumbotron.js
components/schedule/data.js

I updated the main schedule and updated the venue on the main page

update schedule and venue

---

app/layout.js
tailwind.config.js

Raleway is the font used throughout our documents

change website font to Raleway

---

components/schedule/data.js
components/schedule/schedule-panel.jsx
components/schedule/schedule-step.jsx

feat: adjust schedule

---

app/travel-guide/page.jsx
components/ui/navbar.js

- added some accommodation options
- added transportation guide

add travel guide page

---

app/layout.js
components/home/sections/contact.js
components/home/sections/newsletter.js
package-lock.json
package.json

**Description:**
This pull request enhances both the contact section and the newsletter section which are seen on the home page by implementing toast notifications using the `react-toastify` library. Toast notifications are displayed to provide real-time feedback to users when they submit the contact form. 
**Changes Made:**
- Integrated the `react-toastify` library into the project.
- Created a function to display success and error toast messages.
- Modified the form submission handling logic to trigger toast messages when the forms are submitted successfully or encounters an error.
- Improved the user experience by providing instant feedback on the outcome of the form submission.
**Testing:**
- Tested the form submission functionality and toast notifications under various scenarios, …

Feat "Added Toast Notifications for Form Submissions in the both The Contact Section and Newsletter"

---

2024/utils/constants.js
app/2024/speakers/page.jsx
components/2023/home/sections/contact.js
components/2023/layout/footer.js

CFP updates

---

app/2024/page.js
components/banner.jsx

This PR addresses design inconsistencies in the announcement banner on different screen breakpoints. Here's a summary of the changes:
**Fixes:** Resolved design inconsistencies of the banner component.
**AddOns:** Added a background to the banner to simulate the Uganda flag & PyConUg theme colors (Black, Yellow, Red)
These changes aim to enhance the visual appeal of the website by providing a more catchy announcement banner. Please review and provide feed back. Thanks

Fix: Banner design inconsistencies

---

2024/utils/constants.js
app/2024/django-girls/page.jsx
components/2024/layout/navbar.jsx

- changed the Django girls link to the current on(2024)

feat: add django girls to PyCon 2024 Communities

---

components/2023/layout/footer.js

- added the chair's number and removed the old telephone numbers

update contact phone numbers 

---

components/2024/home/jumbotron.jsx
components/2024/home/tickets.jsx
components/2024/layout/navbar.jsx

The sizes might not be perfect.

change ticket word and expose merch in nav and jumbotron

---

app/2024/keynote-speakers/page.jsx
components/speakers/keynote-speaker-cards.jsx

This pull request introduces a new KeynoteSpeakers component to the project. The component displays a list of keynote speakers in a responsive grid layout, showcasing each speaker's image, name, and social media links (Twitter/X and LinkedIn).

UI: Designed New Keynote Speaker Section

---

app/2024/shop/shop.jsx
app/2024/speakers/speakers.jsx
components/2024/layout/navbar.jsx
components/speakers/keynote-speaker-cards.jsx

This commit updates the merchandise link in the navbar to point to the correct page ("/2024/shop"). It also adds a shopping bag icon next to the link for better visibility.

feat: Update merchandise link in navbar

---

.gitignore
.vscode/settings.json
components/2024/layout/navbar.jsx
sample.md

Change communities to Co-Events

Modify communities
